export const SELECT_ROLE = 'SELECT_ROLE';
export const COMING_SOON_EMAIL_CHANGE = 'COMING_SOON_EMAIL_CHANGE';
export const COMING_SOON_EMAIL_SUCCESS = 'COMING_SOON_EMAIL_SUCCESS';
export const COMING_SOON_EMAIL_SUBMIT = 'COMING_SOON_EMAIL_SUBMIT';
export const COMING_SOON_EMAIL_FAIL = 'COMING_SOON_EMAIL_FAIL';
export const SET_USER_DATA = 'SET_USER_DATA';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
